version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-23-21-148-223.compute-1.amazonaws.com
            database: d519rione42j44
            # schema: public
            user: ojrtfmqmopzwhq
            password: 20989df88bf1a59f2c5cdb29bc3dacf53fd0009cd1cad8ee14f8b1f3513bb0f7
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
